version: '2'
services:
  db:
    image: devopsfora/mysql:REL1
    volumes:
      - "/usr/local/datadir:/var/lib/mysql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
      MYSQL_DATABASE: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: mypassword
  wordpress:
    depends_on:
      - db
    image: devopsfora/wordpress:REL1
    volumes:
      - "/usr/local/www/html:/var/www/html"
    links:
      - db
    ports:
      - "80:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_PASSWORD: mypassword
    restart: always
